/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	authorization_v1alpha1 "github.com/kubedb/user-manager/apis/authorization/v1alpha1"
	versioned "github.com/kubedb/user-manager/client/clientset/versioned"
	internalinterfaces "github.com/kubedb/user-manager/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubedb/user-manager/client/listers/authorization/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MysqlRoleInformer provides access to a shared informer and lister for
// MysqlRoles.
type MysqlRoleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MysqlRoleLister
}

type mysqlRoleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMysqlRoleInformer constructs a new informer for MysqlRole type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMysqlRoleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMysqlRoleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMysqlRoleInformer constructs a new informer for MysqlRole type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMysqlRoleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AuthorizationV1alpha1().MysqlRoles(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AuthorizationV1alpha1().MysqlRoles(namespace).Watch(options)
			},
		},
		&authorization_v1alpha1.MysqlRole{},
		resyncPeriod,
		indexers,
	)
}

func (f *mysqlRoleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMysqlRoleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mysqlRoleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&authorization_v1alpha1.MysqlRole{}, f.defaultInformer)
}

func (f *mysqlRoleInformer) Lister() v1alpha1.MysqlRoleLister {
	return v1alpha1.NewMysqlRoleLister(f.Informer().GetIndexer())
}
