/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubedb/user-manager/apis/authorization/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMongodbRoles implements MongodbRoleInterface
type FakeMongodbRoles struct {
	Fake *FakeAuthorizationV1alpha1
	ns   string
}

var mongodbrolesResource = schema.GroupVersionResource{Group: "authorization.kubedb.com", Version: "v1alpha1", Resource: "mongodbroles"}

var mongodbrolesKind = schema.GroupVersionKind{Group: "authorization.kubedb.com", Version: "v1alpha1", Kind: "MongodbRole"}

// Get takes name of the mongodbRole, and returns the corresponding mongodbRole object, and an error if there is any.
func (c *FakeMongodbRoles) Get(name string, options v1.GetOptions) (result *v1alpha1.MongodbRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mongodbrolesResource, c.ns, name), &v1alpha1.MongodbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRole), err
}

// List takes label and field selectors, and returns the list of MongodbRoles that match those selectors.
func (c *FakeMongodbRoles) List(opts v1.ListOptions) (result *v1alpha1.MongodbRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mongodbrolesResource, mongodbrolesKind, c.ns, opts), &v1alpha1.MongodbRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MongodbRoleList{ListMeta: obj.(*v1alpha1.MongodbRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.MongodbRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mongodbRoles.
func (c *FakeMongodbRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mongodbrolesResource, c.ns, opts))

}

// Create takes the representation of a mongodbRole and creates it.  Returns the server's representation of the mongodbRole, and an error, if there is any.
func (c *FakeMongodbRoles) Create(mongodbRole *v1alpha1.MongodbRole) (result *v1alpha1.MongodbRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mongodbrolesResource, c.ns, mongodbRole), &v1alpha1.MongodbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRole), err
}

// Update takes the representation of a mongodbRole and updates it. Returns the server's representation of the mongodbRole, and an error, if there is any.
func (c *FakeMongodbRoles) Update(mongodbRole *v1alpha1.MongodbRole) (result *v1alpha1.MongodbRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mongodbrolesResource, c.ns, mongodbRole), &v1alpha1.MongodbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMongodbRoles) UpdateStatus(mongodbRole *v1alpha1.MongodbRole) (*v1alpha1.MongodbRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mongodbrolesResource, "status", c.ns, mongodbRole), &v1alpha1.MongodbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRole), err
}

// Delete takes name of the mongodbRole and deletes it. Returns an error if one occurs.
func (c *FakeMongodbRoles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mongodbrolesResource, c.ns, name), &v1alpha1.MongodbRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMongodbRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mongodbrolesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MongodbRoleList{})
	return err
}

// Patch applies the patch and returns the patched mongodbRole.
func (c *FakeMongodbRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MongodbRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mongodbrolesResource, c.ns, name, data, subresources...), &v1alpha1.MongodbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRole), err
}
