/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubedb/user-manager/apis/authorization/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMongodbRoleBindings implements MongodbRoleBindingInterface
type FakeMongodbRoleBindings struct {
	Fake *FakeAuthorizationV1alpha1
	ns   string
}

var mongodbrolebindingsResource = schema.GroupVersionResource{Group: "authorization.kubedb.com", Version: "v1alpha1", Resource: "mongodbrolebindings"}

var mongodbrolebindingsKind = schema.GroupVersionKind{Group: "authorization.kubedb.com", Version: "v1alpha1", Kind: "MongodbRoleBinding"}

// Get takes name of the mongodbRoleBinding, and returns the corresponding mongodbRoleBinding object, and an error if there is any.
func (c *FakeMongodbRoleBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.MongodbRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mongodbrolebindingsResource, c.ns, name), &v1alpha1.MongodbRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRoleBinding), err
}

// List takes label and field selectors, and returns the list of MongodbRoleBindings that match those selectors.
func (c *FakeMongodbRoleBindings) List(opts v1.ListOptions) (result *v1alpha1.MongodbRoleBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mongodbrolebindingsResource, mongodbrolebindingsKind, c.ns, opts), &v1alpha1.MongodbRoleBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MongodbRoleBindingList{ListMeta: obj.(*v1alpha1.MongodbRoleBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.MongodbRoleBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mongodbRoleBindings.
func (c *FakeMongodbRoleBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mongodbrolebindingsResource, c.ns, opts))

}

// Create takes the representation of a mongodbRoleBinding and creates it.  Returns the server's representation of the mongodbRoleBinding, and an error, if there is any.
func (c *FakeMongodbRoleBindings) Create(mongodbRoleBinding *v1alpha1.MongodbRoleBinding) (result *v1alpha1.MongodbRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mongodbrolebindingsResource, c.ns, mongodbRoleBinding), &v1alpha1.MongodbRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRoleBinding), err
}

// Update takes the representation of a mongodbRoleBinding and updates it. Returns the server's representation of the mongodbRoleBinding, and an error, if there is any.
func (c *FakeMongodbRoleBindings) Update(mongodbRoleBinding *v1alpha1.MongodbRoleBinding) (result *v1alpha1.MongodbRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mongodbrolebindingsResource, c.ns, mongodbRoleBinding), &v1alpha1.MongodbRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRoleBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMongodbRoleBindings) UpdateStatus(mongodbRoleBinding *v1alpha1.MongodbRoleBinding) (*v1alpha1.MongodbRoleBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mongodbrolebindingsResource, "status", c.ns, mongodbRoleBinding), &v1alpha1.MongodbRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRoleBinding), err
}

// Delete takes name of the mongodbRoleBinding and deletes it. Returns an error if one occurs.
func (c *FakeMongodbRoleBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mongodbrolebindingsResource, c.ns, name), &v1alpha1.MongodbRoleBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMongodbRoleBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mongodbrolebindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MongodbRoleBindingList{})
	return err
}

// Patch applies the patch and returns the patched mongodbRoleBinding.
func (c *FakeMongodbRoleBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MongodbRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mongodbrolebindingsResource, c.ns, name, data, subresources...), &v1alpha1.MongodbRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongodbRoleBinding), err
}
