/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubedb/user-manager/apis/authorization/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMysqlRoles implements MysqlRoleInterface
type FakeMysqlRoles struct {
	Fake *FakeAuthorizationV1alpha1
	ns   string
}

var mysqlrolesResource = schema.GroupVersionResource{Group: "authorization.kubedb.com", Version: "v1alpha1", Resource: "mysqlroles"}

var mysqlrolesKind = schema.GroupVersionKind{Group: "authorization.kubedb.com", Version: "v1alpha1", Kind: "MysqlRole"}

// Get takes name of the mysqlRole, and returns the corresponding mysqlRole object, and an error if there is any.
func (c *FakeMysqlRoles) Get(name string, options v1.GetOptions) (result *v1alpha1.MysqlRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mysqlrolesResource, c.ns, name), &v1alpha1.MysqlRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRole), err
}

// List takes label and field selectors, and returns the list of MysqlRoles that match those selectors.
func (c *FakeMysqlRoles) List(opts v1.ListOptions) (result *v1alpha1.MysqlRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mysqlrolesResource, mysqlrolesKind, c.ns, opts), &v1alpha1.MysqlRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MysqlRoleList{ListMeta: obj.(*v1alpha1.MysqlRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.MysqlRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mysqlRoles.
func (c *FakeMysqlRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mysqlrolesResource, c.ns, opts))

}

// Create takes the representation of a mysqlRole and creates it.  Returns the server's representation of the mysqlRole, and an error, if there is any.
func (c *FakeMysqlRoles) Create(mysqlRole *v1alpha1.MysqlRole) (result *v1alpha1.MysqlRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mysqlrolesResource, c.ns, mysqlRole), &v1alpha1.MysqlRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRole), err
}

// Update takes the representation of a mysqlRole and updates it. Returns the server's representation of the mysqlRole, and an error, if there is any.
func (c *FakeMysqlRoles) Update(mysqlRole *v1alpha1.MysqlRole) (result *v1alpha1.MysqlRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mysqlrolesResource, c.ns, mysqlRole), &v1alpha1.MysqlRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMysqlRoles) UpdateStatus(mysqlRole *v1alpha1.MysqlRole) (*v1alpha1.MysqlRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mysqlrolesResource, "status", c.ns, mysqlRole), &v1alpha1.MysqlRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRole), err
}

// Delete takes name of the mysqlRole and deletes it. Returns an error if one occurs.
func (c *FakeMysqlRoles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mysqlrolesResource, c.ns, name), &v1alpha1.MysqlRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMysqlRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mysqlrolesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MysqlRoleList{})
	return err
}

// Patch applies the patch and returns the patched mysqlRole.
func (c *FakeMysqlRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MysqlRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mysqlrolesResource, c.ns, name, data, subresources...), &v1alpha1.MysqlRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRole), err
}
