/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubedb/user-manager/apis/authorization/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMysqlRoleBindings implements MysqlRoleBindingInterface
type FakeMysqlRoleBindings struct {
	Fake *FakeAuthorizationV1alpha1
	ns   string
}

var mysqlrolebindingsResource = schema.GroupVersionResource{Group: "authorization.kubedb.com", Version: "v1alpha1", Resource: "mysqlrolebindings"}

var mysqlrolebindingsKind = schema.GroupVersionKind{Group: "authorization.kubedb.com", Version: "v1alpha1", Kind: "MysqlRoleBinding"}

// Get takes name of the mysqlRoleBinding, and returns the corresponding mysqlRoleBinding object, and an error if there is any.
func (c *FakeMysqlRoleBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.MysqlRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mysqlrolebindingsResource, c.ns, name), &v1alpha1.MysqlRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRoleBinding), err
}

// List takes label and field selectors, and returns the list of MysqlRoleBindings that match those selectors.
func (c *FakeMysqlRoleBindings) List(opts v1.ListOptions) (result *v1alpha1.MysqlRoleBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mysqlrolebindingsResource, mysqlrolebindingsKind, c.ns, opts), &v1alpha1.MysqlRoleBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MysqlRoleBindingList{ListMeta: obj.(*v1alpha1.MysqlRoleBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.MysqlRoleBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mysqlRoleBindings.
func (c *FakeMysqlRoleBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mysqlrolebindingsResource, c.ns, opts))

}

// Create takes the representation of a mysqlRoleBinding and creates it.  Returns the server's representation of the mysqlRoleBinding, and an error, if there is any.
func (c *FakeMysqlRoleBindings) Create(mysqlRoleBinding *v1alpha1.MysqlRoleBinding) (result *v1alpha1.MysqlRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mysqlrolebindingsResource, c.ns, mysqlRoleBinding), &v1alpha1.MysqlRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRoleBinding), err
}

// Update takes the representation of a mysqlRoleBinding and updates it. Returns the server's representation of the mysqlRoleBinding, and an error, if there is any.
func (c *FakeMysqlRoleBindings) Update(mysqlRoleBinding *v1alpha1.MysqlRoleBinding) (result *v1alpha1.MysqlRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mysqlrolebindingsResource, c.ns, mysqlRoleBinding), &v1alpha1.MysqlRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRoleBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMysqlRoleBindings) UpdateStatus(mysqlRoleBinding *v1alpha1.MysqlRoleBinding) (*v1alpha1.MysqlRoleBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mysqlrolebindingsResource, "status", c.ns, mysqlRoleBinding), &v1alpha1.MysqlRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRoleBinding), err
}

// Delete takes name of the mysqlRoleBinding and deletes it. Returns an error if one occurs.
func (c *FakeMysqlRoleBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mysqlrolebindingsResource, c.ns, name), &v1alpha1.MysqlRoleBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMysqlRoleBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mysqlrolebindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MysqlRoleBindingList{})
	return err
}

// Patch applies the patch and returns the patched mysqlRoleBinding.
func (c *FakeMysqlRoleBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MysqlRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mysqlrolebindingsResource, c.ns, name, data, subresources...), &v1alpha1.MysqlRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlRoleBinding), err
}
