/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubedb/user-manager/apis/authorization/v1alpha1"
	scheme "github.com/kubedb/user-manager/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MongodbRolesGetter has a method to return a MongodbRoleInterface.
// A group's client should implement this interface.
type MongodbRolesGetter interface {
	MongodbRoles(namespace string) MongodbRoleInterface
}

// MongodbRoleInterface has methods to work with MongodbRole resources.
type MongodbRoleInterface interface {
	Create(*v1alpha1.MongodbRole) (*v1alpha1.MongodbRole, error)
	Update(*v1alpha1.MongodbRole) (*v1alpha1.MongodbRole, error)
	UpdateStatus(*v1alpha1.MongodbRole) (*v1alpha1.MongodbRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MongodbRole, error)
	List(opts v1.ListOptions) (*v1alpha1.MongodbRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MongodbRole, err error)
	MongodbRoleExpansion
}

// mongodbRoles implements MongodbRoleInterface
type mongodbRoles struct {
	client rest.Interface
	ns     string
}

// newMongodbRoles returns a MongodbRoles
func newMongodbRoles(c *AuthorizationV1alpha1Client, namespace string) *mongodbRoles {
	return &mongodbRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mongodbRole, and returns the corresponding mongodbRole object, and an error if there is any.
func (c *mongodbRoles) Get(name string, options v1.GetOptions) (result *v1alpha1.MongodbRole, err error) {
	result = &v1alpha1.MongodbRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mongodbroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MongodbRoles that match those selectors.
func (c *mongodbRoles) List(opts v1.ListOptions) (result *v1alpha1.MongodbRoleList, err error) {
	result = &v1alpha1.MongodbRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mongodbroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mongodbRoles.
func (c *mongodbRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mongodbroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a mongodbRole and creates it.  Returns the server's representation of the mongodbRole, and an error, if there is any.
func (c *mongodbRoles) Create(mongodbRole *v1alpha1.MongodbRole) (result *v1alpha1.MongodbRole, err error) {
	result = &v1alpha1.MongodbRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mongodbroles").
		Body(mongodbRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a mongodbRole and updates it. Returns the server's representation of the mongodbRole, and an error, if there is any.
func (c *mongodbRoles) Update(mongodbRole *v1alpha1.MongodbRole) (result *v1alpha1.MongodbRole, err error) {
	result = &v1alpha1.MongodbRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mongodbroles").
		Name(mongodbRole.Name).
		Body(mongodbRole).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *mongodbRoles) UpdateStatus(mongodbRole *v1alpha1.MongodbRole) (result *v1alpha1.MongodbRole, err error) {
	result = &v1alpha1.MongodbRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mongodbroles").
		Name(mongodbRole.Name).
		SubResource("status").
		Body(mongodbRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the mongodbRole and deletes it. Returns an error if one occurs.
func (c *mongodbRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mongodbroles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mongodbRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mongodbroles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched mongodbRole.
func (c *mongodbRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MongodbRole, err error) {
	result = &v1alpha1.MongodbRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mongodbroles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
