/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubedb/user-manager/apis/authorization/v1alpha1"
	scheme "github.com/kubedb/user-manager/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MysqlRolesGetter has a method to return a MysqlRoleInterface.
// A group's client should implement this interface.
type MysqlRolesGetter interface {
	MysqlRoles(namespace string) MysqlRoleInterface
}

// MysqlRoleInterface has methods to work with MysqlRole resources.
type MysqlRoleInterface interface {
	Create(*v1alpha1.MysqlRole) (*v1alpha1.MysqlRole, error)
	Update(*v1alpha1.MysqlRole) (*v1alpha1.MysqlRole, error)
	UpdateStatus(*v1alpha1.MysqlRole) (*v1alpha1.MysqlRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MysqlRole, error)
	List(opts v1.ListOptions) (*v1alpha1.MysqlRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MysqlRole, err error)
	MysqlRoleExpansion
}

// mysqlRoles implements MysqlRoleInterface
type mysqlRoles struct {
	client rest.Interface
	ns     string
}

// newMysqlRoles returns a MysqlRoles
func newMysqlRoles(c *AuthorizationV1alpha1Client, namespace string) *mysqlRoles {
	return &mysqlRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mysqlRole, and returns the corresponding mysqlRole object, and an error if there is any.
func (c *mysqlRoles) Get(name string, options v1.GetOptions) (result *v1alpha1.MysqlRole, err error) {
	result = &v1alpha1.MysqlRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mysqlroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MysqlRoles that match those selectors.
func (c *mysqlRoles) List(opts v1.ListOptions) (result *v1alpha1.MysqlRoleList, err error) {
	result = &v1alpha1.MysqlRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mysqlroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mysqlRoles.
func (c *mysqlRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mysqlroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a mysqlRole and creates it.  Returns the server's representation of the mysqlRole, and an error, if there is any.
func (c *mysqlRoles) Create(mysqlRole *v1alpha1.MysqlRole) (result *v1alpha1.MysqlRole, err error) {
	result = &v1alpha1.MysqlRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mysqlroles").
		Body(mysqlRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a mysqlRole and updates it. Returns the server's representation of the mysqlRole, and an error, if there is any.
func (c *mysqlRoles) Update(mysqlRole *v1alpha1.MysqlRole) (result *v1alpha1.MysqlRole, err error) {
	result = &v1alpha1.MysqlRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mysqlroles").
		Name(mysqlRole.Name).
		Body(mysqlRole).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *mysqlRoles) UpdateStatus(mysqlRole *v1alpha1.MysqlRole) (result *v1alpha1.MysqlRole, err error) {
	result = &v1alpha1.MysqlRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mysqlroles").
		Name(mysqlRole.Name).
		SubResource("status").
		Body(mysqlRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the mysqlRole and deletes it. Returns an error if one occurs.
func (c *mysqlRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mysqlroles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mysqlRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mysqlroles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched mysqlRole.
func (c *mysqlRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MysqlRole, err error) {
	result = &v1alpha1.MysqlRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mysqlroles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
