/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubedb/user-manager/apis/users/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMessagingServices implements MessagingServiceInterface
type FakeMessagingServices struct {
	Fake *FakeUsersV1alpha1
	ns   string
}

var messagingservicesResource = schema.GroupVersionResource{Group: "users.kubedb.com", Version: "v1alpha1", Resource: "messagingservices"}

var messagingservicesKind = schema.GroupVersionKind{Group: "users.kubedb.com", Version: "v1alpha1", Kind: "MessagingService"}

// Get takes name of the messagingService, and returns the corresponding messagingService object, and an error if there is any.
func (c *FakeMessagingServices) Get(name string, options v1.GetOptions) (result *v1alpha1.MessagingService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(messagingservicesResource, c.ns, name), &v1alpha1.MessagingService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MessagingService), err
}

// List takes label and field selectors, and returns the list of MessagingServices that match those selectors.
func (c *FakeMessagingServices) List(opts v1.ListOptions) (result *v1alpha1.MessagingServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(messagingservicesResource, messagingservicesKind, c.ns, opts), &v1alpha1.MessagingServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MessagingServiceList{ListMeta: obj.(*v1alpha1.MessagingServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.MessagingServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested messagingServices.
func (c *FakeMessagingServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(messagingservicesResource, c.ns, opts))

}

// Create takes the representation of a messagingService and creates it.  Returns the server's representation of the messagingService, and an error, if there is any.
func (c *FakeMessagingServices) Create(messagingService *v1alpha1.MessagingService) (result *v1alpha1.MessagingService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(messagingservicesResource, c.ns, messagingService), &v1alpha1.MessagingService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MessagingService), err
}

// Update takes the representation of a messagingService and updates it. Returns the server's representation of the messagingService, and an error, if there is any.
func (c *FakeMessagingServices) Update(messagingService *v1alpha1.MessagingService) (result *v1alpha1.MessagingService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(messagingservicesResource, c.ns, messagingService), &v1alpha1.MessagingService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MessagingService), err
}

// Delete takes name of the messagingService and deletes it. Returns an error if one occurs.
func (c *FakeMessagingServices) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(messagingservicesResource, c.ns, name), &v1alpha1.MessagingService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMessagingServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(messagingservicesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MessagingServiceList{})
	return err
}

// Patch applies the patch and returns the patched messagingService.
func (c *FakeMessagingServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MessagingService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(messagingservicesResource, c.ns, name, data, subresources...), &v1alpha1.MessagingService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MessagingService), err
}
