/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// MongodbRoleListerExpansion allows custom methods to be added to
// MongodbRoleLister.
type MongodbRoleListerExpansion interface{}

// MongodbRoleNamespaceListerExpansion allows custom methods to be added to
// MongodbRoleNamespaceLister.
type MongodbRoleNamespaceListerExpansion interface{}

// MysqlRoleListerExpansion allows custom methods to be added to
// MysqlRoleLister.
type MysqlRoleListerExpansion interface{}

// MysqlRoleNamespaceListerExpansion allows custom methods to be added to
// MysqlRoleNamespaceLister.
type MysqlRoleNamespaceListerExpansion interface{}

// MysqlRoleBindingListerExpansion allows custom methods to be added to
// MysqlRoleBindingLister.
type MysqlRoleBindingListerExpansion interface{}

// MysqlRoleBindingNamespaceListerExpansion allows custom methods to be added to
// MysqlRoleBindingNamespaceLister.
type MysqlRoleBindingNamespaceListerExpansion interface{}

// PostgresRoleListerExpansion allows custom methods to be added to
// PostgresRoleLister.
type PostgresRoleListerExpansion interface{}

// PostgresRoleNamespaceListerExpansion allows custom methods to be added to
// PostgresRoleNamespaceLister.
type PostgresRoleNamespaceListerExpansion interface{}

// PostgresRoleBindingListerExpansion allows custom methods to be added to
// PostgresRoleBindingLister.
type PostgresRoleBindingListerExpansion interface{}

// PostgresRoleBindingNamespaceListerExpansion allows custom methods to be added to
// PostgresRoleBindingNamespaceLister.
type PostgresRoleBindingNamespaceListerExpansion interface{}
